import "./about.scss"
import Link from "next/link"
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: "about",
    description: "Generated by create next app",
}

const page = () => {
    return (
        <div className="about">
            <div>page</div>
            <Link href="/">Link to home page</Link>
        </div>
    )
}

export default page
